<?php

namespace AppBundle\Repository;

/**
 * ComplaintsRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class ComplaintsRepository extends AppRepository
{
}
