<?php

namespace AppBundle\Repository;

/**
 * DefectivesRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class DefectivesRepository extends AppRepository
{
}
