<?php

namespace AppBundle\Repository;

/**
 * DeliveriesRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class DeliveriesRepository extends AppRepository
{
}
