<?php

namespace AppBundle\Repository;

/**
 * ModelsRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class ModelsRepository extends AppRepository
{
    // protected function getQueryFields($type=''){
    //     return array_merge(parent::getQueryFields($type),
    //         $this->addJoinedFields('upload', ['name','url']));
    // }
    
    // public function getDic($options=[])
    // {
    //     $this->getDicNames();
    //     $options['order']='e.sequence';
    //     return parent::getDic($options);
    // }
}
