<?php

namespace AppBundle\Repository;

/**
 * PositionsRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class PositionsRepository extends AppRepository
{
}
