<?php

namespace AppBundle\Repository;
use AppBundle\Utils\Utils;

/**
 * PriceListItemsRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class PriceListItemsRepository extends AppRepository
{
    public function getUniques($options=[]){
        $this->init();
        $this->query="e.id, CONCAT(e_size.id, '_', e_color.id) AS unique";
        $this->toJoin=[['size'], ['color']];
        $this->selectFrom();
        $rows=$this->getResult();
        $ret=[];
        foreach ($rows as $row) {
            $ret[$row['unique']]=$row['id'];
        }
        return $ret;
    }
    
    public function getDic($options = [])
    {
        Utils::deep_array_value_set('order', $options, 'name');
        return parent::getDic($options);
    }

    public function getListToPriceList($options=[]){
        $this->init();
        if (!isset($options['query'])) {
            $options['query'] = $this->generateQuery($this->getQueryFields('to_pricelist'));
        }
        Utils::deep_array_value_set('filters-active', $options, $this->activeFilter['active']);
        return $this->action($options);
    }
}
