<?php

namespace AppBundle\Repository;

/**
 * PricesRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class PricesRepository extends AppRepository
{
}
