<?php

namespace AppBundle\Repository;

/**
 * SizesRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class SizesRepository extends AppRepository
{
    
    // public function getDic($options=[]){
    //     // $this->getDicNames();
    //     // $options['order']='e.sequence';
    //     return parent::getDic($options);
    // }
}
