app_admin_models:
    path:     /
    defaults: { _controller: AppBundle\Controller\ModelsController::indexAction }

app_admin_models_ajax:
    path:     /ajax
    defaults: { _controller: AppBundle\Controller\ModelsController::ajaxListAction }

app_admin_models_dic:
    path:     /dic
    defaults: { _controller: AppBundle\Controller\ModelsController::ajaxDicAction }

app_admin_models_data:
    path:     /{id}/data
    defaults: { _controller: AppBundle\Controller\ModelsController::ajaxDataAction }

app_admin_models_show:
    path:     /{id}/show
    defaults: { _controller: AppBundle\Controller\ModelsController::showAction }

app_admin_models_new:
    path:     /new
    defaults: { _controller: AppBundle\Controller\ModelsController::newAction }

app_admin_models_create:
    path:     /create
    defaults: { _controller: AppBundle\Controller\ModelsController::createAction }
    methods:  POST

app_admin_models_edit:
    path:     /{id}/edit
    defaults: { _controller: AppBundle\Controller\ModelsController::editAction }

app_admin_models_update:
    path:     /{id}/update
    defaults: { _controller: AppBundle\Controller\ModelsController::updateAction }
    methods:  [POST, PUT]

app_admin_models_delete:
    path:     /{id}/delete
    defaults: { _controller: AppBundle\Controller\ModelsController::deleteAction }

app_admin_models_remove:
    path:     /{id}/remove
    defaults: { _controller: AppBundle\Controller\ModelsController::removeAction }
    methods:  [POST, DELETE]
