app_admin_orders:
    path:     /
    defaults: { _controller: AppBundle\Controller\OrdersController::indexAction }

app_admin_orders_ajax:
    path:     /ajax
    defaults: { _controller: AppBundle\Controller\OrdersController::ajaxListAction }    

app_admin_orders_ajax_to_production:
    path:     /ajax_to_production
    defaults: { _controller: AppBundle\Controller\OrdersController::ajaxListToProductionAction }    

app_admin_orders_ajax_to_delivery:
    path:     /ajax_to_delivery
    defaults: { _controller: AppBundle\Controller\OrdersController::ajaxListToDeliveryAction }    

app_admin_orders_dic:
    path:     /dic
    defaults: { _controller: AppBundle\Controller\OrdersController::ajaxDicAction }

app_admin_orders_ajax_details:
    path:     /ajax/details
    defaults: { _controller: AppBundle\Controller\OrdersController::ajaxListDetailsAction }    

app_admin_orders_new:
    path:     /new
    defaults: { _controller: AppBundle\Controller\OrdersController::newAction }

app_admin_orders_create:
    path:     /create
    defaults: { _controller: AppBundle\Controller\OrdersController::createAction }
    methods:  POST

app_admin_orders_edit:
    path:     /{id}/edit
    defaults: { _controller: AppBundle\Controller\OrdersController::editAction }

app_admin_orders_update:
    path:     /{id}/update
    defaults: { _controller: AppBundle\Controller\OrdersController::updateAction }
    methods:  [POST, PUT]

app_admin_orders_delete:
    path:     /{id}/delete
    defaults: { _controller: AppBundle\Controller\OrdersController::deleteAction }

app_admin_orders_remove:
    path:     /{id}/remove
    defaults: { _controller: AppBundle\Controller\OrdersController::removeAction }
    methods:  [POST, DELETE]

app_admin_orders_show:
    path:     /{id}/show
    defaults: { _controller: AppBundle\Controller\OrdersController::showAction }

app_admin_orders_data:
    path:     /{id}/data
    defaults: { _controller: AppBundle\Controller\OrdersController::ajaxDataAction }    

app_admin_orders_import:
    path:     /import
    defaults: { _controller: AppBundle\Controller\OrdersController::importAction }

app_admin_orders_doimport:
    path:     /doimport
    defaults: { _controller: AppBundle\Controller\OrdersController::doimportAction }
    methods:  [POST, PUT]

app_admin_orders_production:
    path:     /production
    defaults: { _controller: AppBundle\Controller\ProductionsController::createAction }
    methods:  POST

app_admin_orders_client:
    path:     /{cid}/client
    defaults: { _controller: AppBundle\Controller\OrdersController::clientIndexAction }

app_admin_orders_client_ajax:
    path:     /{cid}/client/ajax
    defaults: { _controller: AppBundle\Controller\OrdersController::clientAjaxListAction }    

app_admin_orders_client_new:
    path:     /{cid}/client/new
    defaults: { _controller: AppBundle\Controller\OrdersController::newAction }

app_admin_orders_client_create:
    path:     /{cid}/client/create
    defaults: { _controller: AppBundle\Controller\OrdersController::createAction }
    methods:  POST

app_admin_orders_client_edit:
    path:     /{cid}/client/{id}/edit
    defaults: { _controller: AppBundle\Controller\OrdersController::editAction }

app_admin_orders_client_update:
    path:     /{cid}/client/{id}/update
    defaults: { _controller: AppBundle\Controller\OrdersController::updateAction }
    methods:  [POST, PUT]

app_admin_orders_client_delete:
    path:     /{cid}/client/{id}/delete
    defaults: { _controller: AppBundle\Controller\OrdersController::deleteAction }

app_admin_orders_client_remove:
    path:     /{cid}/client/{id}/remove
    defaults: { _controller: AppBundle\Controller\OrdersController::removeAction }
    methods:  [POST, DELETE]

