app_admin_prices:
    path:     /
    defaults: { _controller: AppBundle\Controller\PricesController::indexAction }

app_admin_prices_ajax:
    path:     /ajax
    defaults: { _controller: AppBundle\Controller\PricesController::ajaxListAction }

app_admin_prices_dic:
    path:     /dic
    defaults: { _controller: AppBundle\Controller\PricesController::ajaxDicAction }

app_admin_prices_data:
    path:     /{id}/data
    defaults: { _controller: AppBundle\Controller\PricesController::ajaxDataAction }

app_admin_prices_show:
    path:     /{id}/show
    defaults: { _controller: AppBundle\Controller\PricesController::showAction }

app_admin_prices_new:
    path:     /new
    defaults: { _controller: AppBundle\Controller\PricesController::newAction }

app_admin_prices_create:
    path:     /create
    defaults: { _controller: AppBundle\Controller\PricesController::createAction }
    methods:  POST

app_admin_prices_edit:
    path:     /{id}/edit
    defaults: { _controller: AppBundle\Controller\PricesController::editAction }

app_admin_prices_update:
    path:     /{id}/update
    defaults: { _controller: AppBundle\Controller\PricesController::updateAction }
    methods:  [POST, PUT]

app_admin_prices_delete:
    path:     /{id}/delete
    defaults: { _controller: AppBundle\Controller\PricesController::deleteAction }

app_admin_prices_remove:
    path:     /{id}/remove
    defaults: { _controller: AppBundle\Controller\PricesController::removeAction }
    methods:  [POST, DELETE]
