app_admin_pricelistitems:
    path:     /
    defaults: { _controller: AppBundle\Controller\PriceListItemsController::indexAction }

app_admin_pricelistitems_ajax:
    path:     /ajax
    defaults: { _controller: AppBundle\Controller\PriceListItemsController::ajaxListAction }

app_admin_pricelistitems_ajax_to_pricelist:
    path:     /ajax_to_pricelist
    defaults: { _controller: AppBundle\Controller\PriceListItemsController::ajaxListToPriceListAction }

app_admin_pricelistitems_dic:
    path:     /dic
    defaults: { _controller: AppBundle\Controller\PriceListItemsController::ajaxDicAction }

app_admin_pricelistitems_data:
    path:     /{id}/data
    defaults: { _controller: AppBundle\Controller\PriceListItemsController::ajaxDataAction }

app_admin_pricelistitems_show:
    path:     /{id}/show
    defaults: { _controller: AppBundle\Controller\PriceListItemsController::showAction }

app_admin_pricelistitems_new:
    path:     /new
    defaults: { _controller: AppBundle\Controller\PriceListItemsController::newAction }

app_admin_pricelistitems_create:
    path:     /create
    defaults: { _controller: AppBundle\Controller\PriceListItemsController::createAction }
    methods:  POST

app_admin_pricelistitems_generate:
    path:     /generate
    defaults: { _controller: AppBundle\Controller\PriceListItemsController::generateAction }

app_admin_pricelistitems_add:
    path:     /add
    defaults: { _controller: AppBundle\Controller\PriceListItemsController::addAction }
    methods:  POST
    
app_admin_pricelistitems_edit:
    path:     /{id}/edit
    defaults: { _controller: AppBundle\Controller\PriceListItemsController::editAction }

app_admin_pricelistitems_update:
    path:     /{id}/update
    defaults: { _controller: AppBundle\Controller\PriceListItemsController::updateAction }
    methods:  [POST, PUT]

app_admin_pricelistitems_delete:
    path:     /{id}/delete
    defaults: { _controller: AppBundle\Controller\PriceListItemsController::deleteAction }

app_admin_pricelistitems_remove:
    path:     /{id}/remove
    defaults: { _controller: AppBundle\Controller\PriceListItemsController::removeAction }
    methods:  [POST, DELETE]
