AppBundle\Entity\Invoices:
    type: entity
    table: Invoices
    repositoryClass: AppBundle\Repository\InvoicesRepository
    id:
        id:
            type: integer
            id: true
            generator:
                strategy: AUTO
            options:
                unsigned: true
    fields:
        created:
            type: datetime
            comment: 'data utworzenia zamówienia'
        term:
            type: datetime
            nullable: true
        number: 
            type: string
            length: 20
    oneToMany:
        orders:
            targetEntity: Orders
            mappedBy: invoice  
            cascade: [ "persist" , "merge"]
        invoiceItems:
            targetEntity: InvoiceItems
            mappedBy: invoice
            cascade: [ "persist" ]
    manyToOne:
        client:
            targetEntity: Clients
            inversedBy: invoices
            joinColumn:
                name: clients_id
                referencedColumnName: id    