AppBundle\Entity\Sizes:
    type: entity
    repositoryClass: AppBundle\Repository\SizesRepository
    entityListeners:
        AppBundle\EntityListener\SizesListener: ~
    table: Sizes
    id:
        id:
            type: integer
            id: true
            generator:
                strategy: IDENTITY
            options:
                unsigned: true
    fields:        
        name:
            type: string
            length: 20
        symbol:
            type: string
            length: 5
        description:
            type: string
            nullable: true
            length: 100
        sequence:
            type: smallint
            nullable: true
            options:
                unsigned: true
        active:
            type: boolean
            options:
                default: true
