AppBundle\Entity\Trims:
    type: entity
    repositoryClass: AppBundle\Repository\TrimsRepository
    entityListeners:
        AppBundle\EntityListener\TrimsListener: ~
    table: Trims
    id:
        id:
            type: integer
            id: true
            generator:
                strategy: IDENTITY
            options:
                unsigned: true
    fields:
        name:
            type: string
            length: 20
        symbol:
            type: string
            length: 5
        description:
            type: string
            nullable: true
            length: 100
        sequence:
            type: smallint
            nullable: true
            options:
                unsigned: true
        active:
            type: boolean
            options:
                default: true
    
    oneToOne:
        upload:
            targetEntity: Uploads
            joinColumn:
                name: uploads_id
                referencedColumnName: id   
            cascade: [ "persist" ]

    lifecycleCallbacks: {  }