AppBundle\Entity\Uploads:
    type: entity
    table: Uploads
    entityListeners:
        AppBundle\EntityListener\UploadsListener: ~
    id:
        id:
            type: integer
            id: true
            generator:
                strategy: AUTO
            options:
                unsigned: true
    fields:
        name:
            type: string
            length: 45
        original:
            type: string
            length: 45
        type:
            type: string
            nullable: true
            length: 20
        size:
            type: integer
            options:
                unsigned: true
        folder:
            type: string
            length: 25
        url:
            type: string
            length: 100
    lifecycleCallbacks: 
           # prePersist: [preUpload]
       # preUpdate: [preUpload]
       # postPersist: [upload]
       # postUpdate: [upload]
        # postRemove: [removeUpload]