uploads_delete:
    path:     /delete
    defaults: { _controller: "AppBundle:Uploads:deleteFile"}
    methods:  [POST, DELETE]

uploads_temp:
    path: /temp
    defaults: { _controller: "AppBundle:Uploads:uploadTemp" }

uploads_uploadfile:
    path:     /send
    defaults: { _controller: "AppBundle:Uploads:uploadFile" }

