app_admin_usersgroups:
    path:     /
    defaults: { _controller: "AppBundle:UsersGroups:index" }

app_admin_usersgroups_ajax:
    path:     /ajax
    defaults: { _controller: "AppBundle:UsersGroups:ajaxList" }

app_admin_usersgroups_create:
    path:     /create
    defaults: { _controller: "AppBundle:UsersGroups:create" }
    methods:  POST

app_admin_usersgroups_data:
    path:     /{id}/data
    defaults: { _controller: "AppBundle:UsersGroups:ajaxData" }

app_admin_usersgroups_delete:
    path:     /{id}/delete
    defaults: { _controller: "AppBundle:UsersGroups:delete" }

app_admin_usersgroups_edit:
    path:     /{id}/edit
    defaults: { _controller: "AppBundle:UsersGroups:edit" }

app_admin_usersgroups_new:
    path:     /new
    defaults: { _controller: "AppBundle:UsersGroups:new" }

app_admin_usersgroups_remove:
    path:     /{id}/remove
    defaults: { _controller: "AppBundle:UsersGroups:remove" }
    methods:  [POST, DELETE]

app_admin_usersgroups_show:
    path:     /{id}/show
    defaults: { _controller: "AppBundle:UsersGroups:show" }

app_admin_usersgroups_update:
    path:     /{id}/update
    defaults: { _controller: "AppBundle:UsersGroups:update" }
    methods:  [POST, PUT]


